services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo_backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 3

  frontend-builder:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: static-export
    volumes:
      - frontend_dist:/srv/frontend

  nginx:
    image: nginx:alpine
    container_name: todo_frontend
    ports:
      - "80:80"
    depends_on:
      - frontend-builder
    volumes:
      - frontend_dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  frontend_dist: